// Auto-generated by TropicalEval`GenerateCppMonteCarlo
// 3 convergent, 0 G0, 0 G1, 0 remainder integrands

#include <complex>
#include <cmath>
#include <random>
#include <fstream>
#include <vector>
#include <iostream>
#include <string>
#include <cassert>
#include <cstdlib>
#include <array>
#ifdef _OPENMP
#include <omp.h>
#endif

using cx = std::complex<double>;

inline cx integrand_conv_0(const double* y, const double* params) {
    // Convergent sector 1
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp(2.0 * log_y[1]);
    P0 += 1.0 * std::exp(2.0 * log_y[0]);

    cx result = 1.0;
    result *= std::exp(-3.0 * std::log(P0));
    return result;
}

inline cx integrand_conv_1(const double* y, const double* params) {
    // Convergent sector 2
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((1.0/2.0) * log_y[0]);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp(2.0 * log_y[1]);

    cx result = (1.0/4.0);
    result *= std::exp(-3.0 * std::log(P0));
    return result;
}

inline cx integrand_conv_2(const double* y, const double* params) {
    // Convergent sector 3
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((1.0/2.0) * log_y[0]);
    P0 += 1.0 * std::exp(2.0 * log_y[1]);
    P0 += 1.0 * std::exp(0.0);

    cx result = (1.0/4.0);
    result *= std::exp(-3.0 * std::log(P0));
    return result;
}

// Function pointer type
using IntegrandFunc = cx(*)(const double*, const double*);

IntegrandFunc integrand_table[] = {
    integrand_conv_0,
    integrand_conv_1,
    integrand_conv_2
};

int integrand_dim[] = {2, 2, 2};
const int N_INTEGRANDS = 3;
const int N_PARAMS = 0;
const int MAX_DIM = 20;

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <input_file> <output_file> [n_samples] [n_threads] [seed_base]" << std::endl;
        return 1;
    }

    std::string input_file = argv[1];
    std::string output_file = argv[2];
    int n_samples = (argc > 3) ? std::atoi(argv[3]) : 1000000;
    int n_threads = (argc > 4) ? std::atoi(argv[4]) : 1;
    // Optional runtime seed override (argv[5]); falls back to compile-time SeedBase.
    uint64_t seed_base = (argc > 5) ? std::strtoull(argv[5], nullptr, 10) : 42ULL;
#ifdef _OPENMP
    if (n_threads == 1) n_threads = omp_get_max_threads();
    omp_set_num_threads(n_threads);
#endif

    // Read kinematic data
    std::ifstream fin(input_file);
    if (!fin) {
        std::cerr << "Cannot open " << input_file << std::endl;
        return 1;
    }

    std::vector<std::vector<double>> kinematic_data;
    if (N_PARAMS == 0) {
        // No kinematic parameters: read count from file, default 1
        int count = 1;
        fin >> count;
        if (count < 1) count = 1;
        for (int i = 0; i < count; i++)
            kinematic_data.push_back({});
    } else {
        double val;
        std::vector<double> row;
        while (fin >> val) {
            row.push_back(val);
            if ((int)row.size() == N_PARAMS) {
                kinematic_data.push_back(row);
                row.clear();
            }
        }
    }
    fin.close();
    int n_kp = (int)kinematic_data.size();
    std::cerr << "Read " << n_kp << " kinematic points" << std::endl;

    std::vector<std::array<double, 4>> results(n_kp);

    #pragma omp parallel for schedule(dynamic)
    for (int kp = 0; kp < n_kp; kp++) {
        const double* params = kinematic_data[kp].data();
        uint64_t seed = seed_base + (uint64_t)kp;
        std::mt19937_64 rng(seed);
        std::uniform_real_distribution<double> dist(0.0, 1.0);

        double total_re = 0.0, total_im = 0.0;
        double total_var_re = 0.0, total_var_im = 0.0;

        for (int s = 0; s < N_INTEGRANDS; s++) {
            int dim = integrand_dim[s];
            double mean_re = 0.0, mean_im = 0.0;
            double M2_re = 0.0, M2_im = 0.0;
#ifdef TROPICAL_MC_DEBUG
            int nan_count = 0;
            double max_mag = 0.0;
#endif

            for (int k = 0; k < n_samples; k++) {
                double y[MAX_DIM];
                for (int i = 0; i < dim; i++) y[i] = dist(rng);

                cx val = integrand_table[s](y, params);

#ifdef TROPICAL_MC_DEBUG
                if (!std::isfinite(val.real()) || !std::isfinite(val.imag())) {
                    nan_count++;
                    if (nan_count <= 5) {
                        std::cerr << "NaN/Inf in sector " << s << " kp=" << kp << " y=[";
                        for (int i = 0; i < dim; i++) std::cerr << y[i] << " ";
                        std::cerr << "]" << std::endl;
                    }
                    continue;
                }
                double mag = std::abs(val);
                if (mag > max_mag) max_mag = mag;
#endif

                double d_re = val.real() - mean_re;
                mean_re += d_re / (k + 1);
                M2_re += d_re * (val.real() - mean_re);
                double d_im = val.imag() - mean_im;
                mean_im += d_im / (k + 1);
                M2_im += d_im * (val.imag() - mean_im);
            }

#ifdef TROPICAL_MC_DEBUG
            if (kp == 0) {
                std::cerr << "Sector " << s << ": mean=(" << mean_re << "," << mean_im
                          << ") max_mag=" << max_mag;
                if (nan_count > 0)
                    std::cerr << " NaN_count=" << nan_count;
                double mean_mag = std::sqrt(mean_re*mean_re + mean_im*mean_im);
                if (mean_mag > 0 && max_mag / mean_mag > 1000)
                    std::cerr << " WARNING: large fluctuations";
                std::cerr << std::endl;
            }
            if ((double)nan_count / n_samples > 0.001)
                std::cerr << "WARNING: >0.1%% NaN in sector " << s << " kp=" << kp << std::endl;
#endif

            total_re += mean_re;
            total_im += mean_im;
            total_var_re += M2_re / ((double)n_samples * (n_samples - 1));
            total_var_im += M2_im / ((double)n_samples * (n_samples - 1));
        }

        results[kp] = {total_re, total_im,
                       std::sqrt(total_var_re), std::sqrt(total_var_im)};
#ifdef TROPICAL_MC_DEBUG
        if (kp == 0) {
            std::cerr << "KP 0 total: (" << total_re << ", " << total_im
                      << ") +/- (" << std::sqrt(total_var_re) << ", "
                      << std::sqrt(total_var_im) << ")" << std::endl;
        }
#endif
    }

    // Write results
    std::ofstream fout(output_file);
    if (!fout) {
        std::cerr << "Cannot open " << output_file << std::endl;
        return 1;
    }
    fout.precision(17);
    for (int kp = 0; kp < n_kp; kp++) {
        fout << results[kp][0] << " " << results[kp][1] << " "
             << results[kp][2] << " " << results[kp][3] << "\n";
    }
    fout.close();

    std::cerr << "Done. Processed " << n_kp << " kinematic points." << std::endl;
    return 0;
}