// Auto-generated by TropicalEval`GenerateCppMonteCarloIBP
// 1 convergent, 12 IBP integrands

#include <complex>
#include <cmath>
#include <random>
#include <fstream>
#include <vector>
#include <iostream>
#include <string>
#include <cassert>
#include <cstdlib>
#include <array>
#ifdef _OPENMP
#include <omp.h>
#endif

using cx = std::complex<double>;

inline cx integrand_conv_0(const double* y, const double* params) {
    // Convergent sector 2
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    // lifted-sector domain indicator
    double log_ypstar = (3.0701134573253945 - (0. * log_y[0] + -0.4444444444444444 * log_y[1])) * (1.0/1.);
    if (log_ypstar > 0.0) return cx(0.0, 0.0);

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((4.0/5.0) * log_y[0]);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp((2.0/3.0) * log_y[1]);
    P0 += 10000.0 * std::exp((4.0/3.0) * log_y[1]);

    cx result = (4.0/15.0);
    result *= std::exp(-2.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0. + -0.8 * log_y[0])) + cx(0.0, 1.0) * (0. + -0.2 * log_y[0] + 0.3333333333333333 * log_y[1]);
    result *= std::exp(phaseSum);
    return result;
}

inline cx integrand_ibp_bnd_0_base(const double* y, const double* params) {
    // IBP boundary base, sector 1
    double log_y[1];
    for (int i = 0; i < 1; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += (1.0/100.0) * std::exp((2.0/3.0) * log_y[0]);
    P0 += 1.0 * std::exp((4.0/3.0) * log_y[0]);

    cx result = (1.0/1000.0);
    result *= std::exp(-2.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0.)) + cx(0.0, 1.0) * (-2.302585092994046 + 0.3333333333333333 * log_y[0]);
    result *= std::exp(phaseSum);
    return result;
}

inline cx integrand_ibp_bnd_0_log(const double* y, const double* params) {
    // IBP boundary log, sector 1
    double log_y[1];
    for (int i = 0; i < 1; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += (1.0/100.0) * std::exp((2.0/3.0) * log_y[0]);
    P0 += 1.0 * std::exp((4.0/3.0) * log_y[0]);

    cx base_val = (1.0/1000.0);
    base_val *= std::exp(-2.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0.)) + cx(0.0, 1.0) * (-2.302585092994046 + 0.3333333333333333 * log_y[0]);
    base_val *= std::exp(phaseSum);

    // Log insertion factors
    cx log_sum(0.0, 0.0);
    log_sum += 0.0 * log_y[0];
    log_sum += -1.0 * std::log(P0);

    return base_val * log_sum;
}

inline cx integrand_ibp_0_t0_base(const double* y, const double* params) {
    // IBP term 0 base, sector 1
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp(1.0 * log_y[1]);
    P0 += (1.0/100.0) * std::exp((2.0/3.0) * log_y[0] + (1.0/2.0) * log_y[1]);
    P0 += 1.0 * std::exp((4.0/3.0) * log_y[0]);

    cx result = (1.0/3000.0);
    result *= std::exp(-3.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0.)) + cx(0.0, 1.0) * (-2.302585092994046 + 0.3333333333333333 * log_y[0]);
    result *= std::exp(phaseSum);
    return result;
}

inline cx integrand_ibp_0_t0_log(const double* y, const double* params) {
    // IBP term 0 log, sector 1
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp(1.0 * log_y[1]);
    P0 += (1.0/100.0) * std::exp((2.0/3.0) * log_y[0] + (1.0/2.0) * log_y[1]);
    P0 += 1.0 * std::exp((4.0/3.0) * log_y[0]);

    cx base_val = (1.0/3000.0);
    base_val *= std::exp(-3.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0.)) + cx(0.0, 1.0) * (-2.302585092994046 + 0.3333333333333333 * log_y[0]);
    base_val *= std::exp(phaseSum);

    cx log_sum(0.0, 0.0);
    log_sum += 0.0 * log_y[0];
    log_sum += (1.0/2.0) * log_y[1];
    log_sum += -1.0 * std::log(P0);

    return base_val * log_sum;
}

inline cx integrand_ibp_0_t1_base(const double* y, const double* params) {
    // IBP term 1 base, sector 1
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp(2.0 * log_y[1]);
    P0 += (1.0/100.0) * std::exp((2.0/5.0) * log_y[0] + 1.0 * log_y[1]);
    P0 += 1.0 * std::exp((4.0/5.0) * log_y[0]);

    cx result = (1.0/2500.0);
    result *= std::exp(-3.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0.)) + cx(0.0, 1.0) * (-2.302585092994046 + 0.2 * log_y[0]);
    result *= std::exp(phaseSum);
    return result;
}

inline cx integrand_ibp_0_t1_log(const double* y, const double* params) {
    // IBP term 1 log, sector 1
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp(2.0 * log_y[1]);
    P0 += (1.0/100.0) * std::exp((2.0/5.0) * log_y[0] + 1.0 * log_y[1]);
    P0 += 1.0 * std::exp((4.0/5.0) * log_y[0]);

    cx base_val = (1.0/2500.0);
    base_val *= std::exp(-3.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0.)) + cx(0.0, 1.0) * (-2.302585092994046 + 0.2 * log_y[0]);
    base_val *= std::exp(phaseSum);

    cx log_sum(0.0, 0.0);
    log_sum += 0.0 * log_y[0];
    log_sum += 1.0 * log_y[1];
    log_sum += -1.0 * std::log(P0);

    return base_val * log_sum;
}

inline cx integrand_ibp_bnd_1_base(const double* y, const double* params) {
    // IBP boundary base, sector 4
    double log_y[1];
    for (int i = 0; i < 1; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((4.0/5.0) * log_y[0]);
    P0 += 1.0 * std::exp(0.0);
    P0 += (1.0/100.0) * std::exp(0.0);
    P0 += 1.0 * std::exp(0.0);

    cx result = (3.0/5000.0);
    result *= std::exp(-2.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0. + -0.8 * log_y[0])) + cx(0.0, 1.0) * (-2.302585092994046 + -0.2 * log_y[0]);
    result *= std::exp(phaseSum);
    return result;
}

inline cx integrand_ibp_bnd_1_log(const double* y, const double* params) {
    // IBP boundary log, sector 4
    double log_y[1];
    for (int i = 0; i < 1; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((4.0/5.0) * log_y[0]);
    P0 += 1.0 * std::exp(0.0);
    P0 += (1.0/100.0) * std::exp(0.0);
    P0 += 1.0 * std::exp(0.0);

    cx base_val = (3.0/5000.0);
    base_val *= std::exp(-2.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0. + -0.8 * log_y[0])) + cx(0.0, 1.0) * (-2.302585092994046 + -0.2 * log_y[0]);
    base_val *= std::exp(phaseSum);

    // Log insertion factors
    cx log_sum(0.0, 0.0);
    log_sum += (2.0/5.0) * log_y[0];
    log_sum += -1.0 * std::log(P0);

    return base_val * log_sum;
}

inline cx integrand_ibp_1_t0_base(const double* y, const double* params) {
    // IBP term 0 base, sector 4
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((4.0/5.0) * log_y[0]);
    P0 += 1.0 * std::exp(1.0 * log_y[1]);
    P0 += (1.0/100.0) * std::exp((1.0/2.0) * log_y[1]);
    P0 += 1.0 * std::exp(0.0);

    cx result = (1.0/5000.0);
    result *= std::exp(-3.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0. + -0.8 * log_y[0])) + cx(0.0, 1.0) * (-2.302585092994046 + -0.2 * log_y[0]);
    result *= std::exp(phaseSum);
    return result;
}

inline cx integrand_ibp_1_t0_log(const double* y, const double* params) {
    // IBP term 0 log, sector 4
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((4.0/5.0) * log_y[0]);
    P0 += 1.0 * std::exp(1.0 * log_y[1]);
    P0 += (1.0/100.0) * std::exp((1.0/2.0) * log_y[1]);
    P0 += 1.0 * std::exp(0.0);

    cx base_val = (1.0/5000.0);
    base_val *= std::exp(-3.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0. + -0.8 * log_y[0])) + cx(0.0, 1.0) * (-2.302585092994046 + -0.2 * log_y[0]);
    base_val *= std::exp(phaseSum);

    cx log_sum(0.0, 0.0);
    log_sum += (2.0/5.0) * log_y[0];
    log_sum += (1.0/2.0) * log_y[1];
    log_sum += -1.0 * std::log(P0);

    return base_val * log_sum;
}

inline cx integrand_ibp_1_t1_base(const double* y, const double* params) {
    // IBP term 1 base, sector 4
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((4.0/5.0) * log_y[0]);
    P0 += 1.0 * std::exp(2.0 * log_y[1]);
    P0 += (1.0/100.0) * std::exp(1.0 * log_y[1]);
    P0 += 1.0 * std::exp(0.0);

    cx result = (1.0/2500.0);
    result *= std::exp(-3.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0. + -0.8 * log_y[0])) + cx(0.0, 1.0) * (-2.302585092994046 + -0.2 * log_y[0]);
    result *= std::exp(phaseSum);
    return result;
}

inline cx integrand_ibp_1_t1_log(const double* y, const double* params) {
    // IBP term 1 log, sector 4
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((4.0/5.0) * log_y[0]);
    P0 += 1.0 * std::exp(2.0 * log_y[1]);
    P0 += (1.0/100.0) * std::exp(1.0 * log_y[1]);
    P0 += 1.0 * std::exp(0.0);

    cx base_val = (1.0/2500.0);
    base_val *= std::exp(-3.0 * std::log(P0));
    // SplitRealImag oscillatory phase (Im(B); complex log P + MonoFactorLog; + Im(A) monomial phase)
    cx phaseSum = cx(0.0, 0.5) * (std::log(P0) + (0. + -0.8 * log_y[0])) + cx(0.0, 1.0) * (-2.302585092994046 + -0.2 * log_y[0]);
    base_val *= std::exp(phaseSum);

    cx log_sum(0.0, 0.0);
    log_sum += (2.0/5.0) * log_y[0];
    log_sum += 1.0 * log_y[1];
    log_sum += -1.0 * std::log(P0);

    return base_val * log_sum;
}

using IntegrandFunc = cx(*)(const double*, const double*);

IntegrandFunc integrand_table[] = {
    integrand_conv_0,
    integrand_ibp_bnd_0_base,
    integrand_ibp_bnd_0_log,
    integrand_ibp_0_t0_base,
    integrand_ibp_0_t0_log,
    integrand_ibp_0_t1_base,
    integrand_ibp_0_t1_log,
    integrand_ibp_bnd_1_base,
    integrand_ibp_bnd_1_log,
    integrand_ibp_1_t0_base,
    integrand_ibp_1_t0_log,
    integrand_ibp_1_t1_base,
    integrand_ibp_1_t1_log
};

int integrand_dim[] = {2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2};
int integrand_type[] = {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
const int N_INTEGRANDS = 13;
const int N_CONV = 1;
const int N_PARAMS = 0;
const int MAX_DIM = 20;

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <input_file> <output_file> [n_samples] [n_threads] [seed_base]" << std::endl;
        return 1;
    }

    std::string input_file = argv[1];
    std::string output_file = argv[2];
    int n_samples = (argc > 3) ? std::atoi(argv[3]) : 1000;
    int n_threads = (argc > 4) ? std::atoi(argv[4]) : 1;
    // Optional runtime seed override (argv[5]); falls back to compile-time SeedBase.
    uint64_t seed_base = (argc > 5) ? std::strtoull(argv[5], nullptr, 10) : 42ULL;
#ifdef _OPENMP
    if (n_threads == 1) n_threads = omp_get_max_threads();
    omp_set_num_threads(n_threads);
#endif

    std::ifstream fin(input_file);
    if (!fin) { std::cerr << "Cannot open " << input_file << std::endl; return 1; }

    std::vector<std::vector<double>> kinematic_data;
    if (N_PARAMS == 0) {
        int count = 1; fin >> count; if (count < 1) count = 1;
        for (int i = 0; i < count; i++) kinematic_data.push_back({});
    } else {
        double val; std::vector<double> row;
        while (fin >> val) { row.push_back(val);
            if ((int)row.size() == N_PARAMS) { kinematic_data.push_back(row); row.clear(); }}
    }
    fin.close();
    int n_kp = (int)kinematic_data.size();
    std::cerr << "Read " << n_kp << " kinematic points" << std::endl;

    // Output: (1 + N_IBP_FUNCS) lines per kinematic point
    // Line 0: convergent sum; Lines 1..N_IBP: individual IBP functions
    int n_ibp = N_INTEGRANDS - N_CONV;
    std::vector<std::array<double, 4>> results((1 + n_ibp) * n_kp);

    #pragma omp parallel for schedule(dynamic)
    for (int kp = 0; kp < n_kp; kp++) {
        const double* params = kinematic_data[kp].data();
        uint64_t seed = seed_base + (uint64_t)kp;
        std::mt19937_64 rng(seed);
        std::uniform_real_distribution<double> dist(0.0, 1.0);

        double conv_re = 0.0, conv_im = 0.0;
        double conv_var_re = 0.0, conv_var_im = 0.0;

        for (int s = 0; s < N_CONV; s++) {
            int dim = integrand_dim[s];
            double mean_re = 0.0, mean_im = 0.0;
            double M2_re = 0.0, M2_im = 0.0;
            for (int k = 0; k < n_samples; k++) {
                double y[MAX_DIM];
                for (int i = 0; i < dim; i++) y[i] = dist(rng);
                cx val = integrand_table[s](y, params);
                double d_re = val.real() - mean_re;
                mean_re += d_re / (k + 1);
                M2_re += d_re * (val.real() - mean_re);
                double d_im = val.imag() - mean_im;
                mean_im += d_im / (k + 1);
                M2_im += d_im * (val.imag() - mean_im);
            }
            conv_re += mean_re; conv_im += mean_im;
            conv_var_re += M2_re / ((double)n_samples * (n_samples - 1));
            conv_var_im += M2_im / ((double)n_samples * (n_samples - 1));
        }
        results[kp * (1 + n_ibp)] = {conv_re, conv_im, std::sqrt(conv_var_re), std::sqrt(conv_var_im)};

        for (int s = N_CONV; s < N_INTEGRANDS; s++) {
            int dim = integrand_dim[s];
            double mean_re = 0.0, mean_im = 0.0;
            double M2_re = 0.0, M2_im = 0.0;
            for (int k = 0; k < n_samples; k++) {
                double y[MAX_DIM];
                for (int i = 0; i < dim; i++) y[i] = dist(rng);
                cx val = integrand_table[s](y, params);
                double d_re = val.real() - mean_re;
                mean_re += d_re / (k + 1);
                M2_re += d_re * (val.real() - mean_re);
                double d_im = val.imag() - mean_im;
                mean_im += d_im / (k + 1);
                M2_im += d_im * (val.imag() - mean_im);
            }
            int idx = kp * (1 + n_ibp) + (s - N_CONV + 1);
            results[idx] = {mean_re, mean_im, std::sqrt(M2_re / ((double)n_samples * (n_samples - 1))), std::sqrt(M2_im / ((double)n_samples * (n_samples - 1)))};
        }
    }

    std::ofstream fout(output_file);
    if (!fout) { std::cerr << "Cannot open " << output_file << std::endl; return 1; }
    fout.precision(17);
    for (int i = 0; i < (int)results.size(); i++) {
        fout << results[i][0] << " " << results[i][1] << " "
             << results[i][2] << " " << results[i][3] << "\n";
    }
    fout.close();
    std::cerr << "Done. Processed " << n_kp << " kinematic points." << std::endl;
    return 0;
}