// Auto-generated by TropicalEval`GenerateCppMonteCarlo
// 1 convergent, 1 G0, 1 G1, 1 remainder integrands

#include <complex>
#include <cmath>
#include <random>
#include <fstream>
#include <vector>
#include <iostream>
#include <string>
#include <cassert>
#include <cstdlib>
#include <array>
#ifdef _OPENMP
#include <omp.h>
#endif

using cx = std::complex<double>;

inline cx integrand_conv_0(const double* y, const double* params) {
    // Convergent sector 2
    double log_y[1];
    for (int i = 0; i < 1; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((1.0/2.0) * log_y[0]);
    P0 += 1.0 * std::exp(0.0);

    cx result = (1.0/2.0);
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

inline cx integrand_g0_0(const double* y, const double* params) {
    // G0 for divergent sector 1
    double log_y[0];
    for (int i = 0; i < 0; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);

    cx result = 1.0;
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

inline cx integrand_g1_0(const double* y, const double* params) {
    // G1 for divergent sector 1
    double log_y[0];
    for (int i = 0; i < 0; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);

    cx g0_val = 1.0;
    g0_val *= std::exp(-2.0 * std::log(P0));

    // Log insertion factors
    cx log_sum(0.0, 0.0);
    log_sum += 0.0 * std::log(P0);

    return g0_val * log_sum;
}

inline cx integrand_rem_0(const double* y, const double* params) {
    // Remainder for divergent sector 1
    double log_y[1];
    for (int i = 0; i < 1; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    // Full polynomials
    cx Pfull0(0.0, 0.0);
    Pfull0 += 1.0 * std::exp(0.0);
    Pfull0 += 1.0 * std::exp(1.0 * log_y[0]);

    // Simplified polynomials (y_k = 0)
    cx Psimp0(0.0, 0.0);
    Psimp0 += 1.0 * std::exp(0.0);

    cx full_prod = std::exp(-2.0 * std::log(Pfull0));
    cx simp_prod = std::exp(-2.0 * std::log(Psimp0));

    cx yk_factor = std::exp(-1.0 * log_y[0]);
    return 1.0 * yk_factor * (full_prod - simp_prod);
}

// Function pointer type
using IntegrandFunc = cx(*)(const double*, const double*);

IntegrandFunc integrand_table[] = {
    integrand_conv_0,
    integrand_g0_0,
    integrand_g1_0,
    integrand_rem_0
};

int integrand_dim[] = {1, 0, 0, 1};
const int N_INTEGRANDS = 4;
const int N_PARAMS = 0;
const int MAX_DIM = 20;

// TROPICAL_REQUIRES_CUBA  (CompileCpp greps for this sentinel)
#ifdef TROPICAL_USE_CUBA
extern "C" {
#include <cuba.h>
}
#include <algorithm>
static const double* gb_par = nullptr;
static int gb_sector = 0, gb_dim = 0, gb_kp0 = 0, gb_chunk = 0;
static int cubaBatch(const int* ndim, const cubareal xx[], const int* ncomp,
                     cubareal ff[], void* userdata) {
    (void)ndim; (void)ncomp; (void)userdata;
    double y[MAX_DIM];
    for (int i = 0; i < gb_dim; ++i) y[i] = (double)xx[i];
    for (int c = 0; c < gb_chunk; ++c) {
        const double* pp = (N_PARAMS > 0) ? &gb_par[(size_t)(gb_kp0 + c) * N_PARAMS] : nullptr;
        cx v = integrand_table[gb_sector](y, pp);
        ff[2*c] = v.real(); ff[2*c + 1] = v.imag();
    }
    return 0;
}
#endif

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <input_file> <output_file> [maxeval] [n_threads]" << std::endl;
        return 1;
    }

    std::string input_file = argv[1];
    std::string output_file = argv[2];
    long long maxeval = (argc > 3) ? std::atoll(argv[3]) : 1000000LL;

    std::ifstream fin(input_file);
    if (!fin) { std::cerr << "Cannot open " << input_file << std::endl; return 1; }
    std::vector<std::vector<double>> kinematic_data;
    if (N_PARAMS == 0) {
        int count = 1; fin >> count; if (count < 1) count = 1;
        for (int i = 0; i < count; i++) kinematic_data.push_back({});
    } else {
        double val; std::vector<double> row;
        while (fin >> val) { row.push_back(val);
            if ((int)row.size() == N_PARAMS) { kinematic_data.push_back(row); row.clear(); }}
    }
    fin.close();
    int n_kp = (int)kinematic_data.size();
    std::cerr << "Read " << n_kp << " kinematic points (Vegas batch)" << std::endl;

    std::vector<std::array<double, 4>> results(n_kp);

#ifdef TROPICAL_USE_CUBA
    { const int zero = 0; cubacores(&zero, &zero); }
    const double epsrel = 1.e-12, epsabs = 1.e-300;
    const int    seed    = 0;
    const int    maxComp = 512;   // ncomp ceiling -- never exceed (Vegas segfaults above it)
    const int    kpPerChunk = (maxComp / 2 < 1) ? 1 : maxComp / 2;  // 2 comps (re,im) per kp
    std::vector<double> flat_par((size_t)n_kp * (N_PARAMS > 0 ? N_PARAMS : 1), 0.0);
    for (int kp = 0; kp < n_kp; ++kp)
        for (int p = 0; p < N_PARAMS; ++p) flat_par[(size_t)kp * N_PARAMS + p] = kinematic_data[kp][p];
    gb_par = flat_par.data();
    std::vector<double> tre(n_kp, 0), tim(n_kp, 0), vre(n_kp, 0), vim(n_kp, 0);
    for (int s = 0; s < N_INTEGRANDS; ++s) {
        gb_sector = s; gb_dim = integrand_dim[s];
        for (int k0 = 0; k0 < n_kp; k0 += kpPerChunk) {
            int cs = std::min(kpPerChunk, n_kp - k0);
            gb_kp0 = k0; gb_chunk = cs;
            int ncomp = 2 * cs;
            std::vector<cubareal> integ(ncomp), err(ncomp), prob(ncomp);
            int neval = 0, fail = 0;
            Vegas(gb_dim, ncomp, cubaBatch, nullptr, 1, epsrel, epsabs, 0, seed,
                  0, (int)maxeval, 1000, 500, 1000, 0, nullptr, nullptr,
                  &neval, &fail, integ.data(), err.data(), prob.data());
            for (int c = 0; c < cs; ++c) {
                tre[k0 + c] += integ[2*c];       tim[k0 + c] += integ[2*c + 1];
                vre[k0 + c] += err[2*c]*err[2*c]; vim[k0 + c] += err[2*c + 1]*err[2*c + 1];
            }
        }
    }
    for (int kp = 0; kp < n_kp; ++kp)
        results[kp] = {tre[kp], tim[kp], std::sqrt(vre[kp]), std::sqrt(vim[kp])};
#else
    (void)maxeval;
    std::cerr << "ERROR: built without CUBA. Rebuild with -DTROPICAL_USE_CUBA "
                 "(install CUBA), or use Integrator -> \"MonteCarlo\"." << std::endl;
    return 2;
#endif

    std::ofstream fout(output_file);
    if (!fout) { std::cerr << "Cannot open " << output_file << std::endl; return 1; }
    fout.precision(17);
    for (int kp = 0; kp < n_kp; kp++) {
        fout << results[kp][0] << " " << results[kp][1] << " "
             << results[kp][2] << " " << results[kp][3] << "\n";
    }
    fout.close();
    std::cerr << "Done. Processed " << n_kp << " kinematic points (batched)." << std::endl;
    return 0;
}