// Auto-generated by TropicalEval`GenerateCppMonteCarlo
// 1 convergent, 1 G0, 1 G1, 1 remainder integrands

#include <complex>
#include <cmath>
#include <random>
#include <fstream>
#include <vector>
#include <iostream>
#include <string>
#include <cassert>
#include <cstdlib>
#include <array>
#ifdef _OPENMP
#include <omp.h>
#endif

using cx = std::complex<double>;

inline cx integrand_conv_0(const double* y, const double* params) {
    // Convergent sector 2
    double log_y[1];
    for (int i = 0; i < 1; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((1.0/2.0) * log_y[0]);
    P0 += 1.0 * std::exp(0.0);

    cx result = (1.0/2.0);
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

inline cx integrand_g0_0(const double* y, const double* params) {
    // G0 for divergent sector 1
    double log_y[0];
    for (int i = 0; i < 0; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);

    cx result = 1.0;
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

inline cx integrand_g1_0(const double* y, const double* params) {
    // G1 for divergent sector 1
    double log_y[0];
    for (int i = 0; i < 0; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);

    cx g0_val = 1.0;
    g0_val *= std::exp(-2.0 * std::log(P0));

    // Log insertion factors
    cx log_sum(0.0, 0.0);
    log_sum += 0.0 * std::log(P0);

    return g0_val * log_sum;
}

inline cx integrand_rem_0(const double* y, const double* params) {
    // Remainder for divergent sector 1
    double log_y[1];
    for (int i = 0; i < 1; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    // Full polynomials
    cx Pfull0(0.0, 0.0);
    Pfull0 += 1.0 * std::exp(0.0);
    Pfull0 += 1.0 * std::exp(1.0 * log_y[0]);

    // Simplified polynomials (y_k = 0)
    cx Psimp0(0.0, 0.0);
    Psimp0 += 1.0 * std::exp(0.0);

    cx full_prod = std::exp(-2.0 * std::log(Pfull0));
    cx simp_prod = std::exp(-2.0 * std::log(Psimp0));

    cx yk_factor = std::exp(-1.0 * log_y[0]);
    return 1.0 * yk_factor * (full_prod - simp_prod);
}

// Function pointer type
using IntegrandFunc = cx(*)(const double*, const double*);

IntegrandFunc integrand_table[] = {
    integrand_conv_0,
    integrand_g0_0,
    integrand_g1_0,
    integrand_rem_0
};

int integrand_dim[] = {1, 0, 0, 1};
const int N_INTEGRANDS = 4;
const int N_PARAMS = 0;
const int MAX_DIM = 20;

// TROPICAL_REQUIRES_CUBA  (CompileCpp greps for this sentinel)
#ifdef TROPICAL_USE_CUBA
extern "C" {
#include <cuba.h>
}
static IntegrandFunc g_fn     = nullptr;
static const double* g_params = nullptr;
static int           g_dim    = 0;
static int cubaWrap(const int* ndim, const cubareal xx[], const int* ncomp,
                    cubareal ff[], void* userdata) {
    (void)ndim; (void)ncomp; (void)userdata;
    double y[MAX_DIM];
    for (int i = 0; i < g_dim; ++i) y[i] = (double)xx[i];
    cx v = g_fn(y, g_params);
    ff[0] = v.real(); ff[1] = v.imag();   // ncomp = 2 (complex integrand)
    return 0;
}
// integrate one sector with Vegas; a 0-dim integrand (e.g. an IBP
// boundary of a 1-var sector) is a constant, so eval it directly.
static void vegasOne(int s, const double* params, long long maxeval,
                     double epsrel, double epsabs, int seed,
                     double out[2], double err[2]) {
    g_fn = integrand_table[s]; g_dim = integrand_dim[s]; g_params = params;
    if (g_dim == 0) {
        double y0[1] = {0.0}; cx v = g_fn(y0, params);
        out[0] = v.real(); out[1] = v.imag(); err[0] = 0.0; err[1] = 0.0;
        return;
    }
    int neval = 0, fail = 0; cubareal I[2], E[2], Pr[2];
    Vegas(g_dim, 2, cubaWrap, nullptr, 1, epsrel, epsabs, 0, seed,
          0, (int)maxeval, 1000, 500, 1000, 0, nullptr, nullptr,
          &neval, &fail, I, E, Pr);
    out[0] = I[0]; out[1] = I[1]; err[0] = E[0]; err[1] = E[1];
}
#endif

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <input_file> <output_file> [maxeval] [n_threads]" << std::endl;
        return 1;
    }

    std::string input_file = argv[1];
    std::string output_file = argv[2];
    long long maxeval = (argc > 3) ? std::atoll(argv[3]) : 1000000LL;

    std::ifstream fin(input_file);
    if (!fin) { std::cerr << "Cannot open " << input_file << std::endl; return 1; }
    std::vector<std::vector<double>> kinematic_data;
    if (N_PARAMS == 0) {
        int count = 1; fin >> count; if (count < 1) count = 1;
        for (int i = 0; i < count; i++) kinematic_data.push_back({});
    } else {
        double val; std::vector<double> row;
        while (fin >> val) { row.push_back(val);
            if ((int)row.size() == N_PARAMS) { kinematic_data.push_back(row); row.clear(); }}
    }
    fin.close();
    int n_kp = (int)kinematic_data.size();
    std::cerr << "Read " << n_kp << " kinematic points (Vegas)" << std::endl;

    std::vector<std::array<double, 4>> results(n_kp);

#ifdef TROPICAL_USE_CUBA
    { const int zero = 0; cubacores(&zero, &zero); }  // single process: deterministic, macOS-safe
    const double epsrel = 1.e-12, epsabs = 1.e-300;
    const int    seed   = 0;
    for (int kp = 0; kp < n_kp; ++kp) {        // SERIAL over kp: CUBA keeps global state
        const double* params = kinematic_data[kp].data();
        double tre = 0, tim = 0, vre = 0, vim = 0;
        for (int s = 0; s < N_INTEGRANDS; ++s) {
            double I[2], E[2]; vegasOne(s, params, maxeval, epsrel, epsabs, seed, I, E);
            tre += I[0]; tim += I[1];
            vre += E[0]*E[0]; vim += E[1]*E[1];
        }
        results[kp] = {tre, tim, std::sqrt(vre), std::sqrt(vim)};
    }
#else
    (void)maxeval;
    std::cerr << "ERROR: built without CUBA. Rebuild with -DTROPICAL_USE_CUBA "
                 "(install CUBA), or use Integrator -> \"MonteCarlo\"." << std::endl;
    return 2;
#endif

    std::ofstream fout(output_file);
    if (!fout) { std::cerr << "Cannot open " << output_file << std::endl; return 1; }
    fout.precision(17);
    for (int kp = 0; kp < n_kp; kp++) {
        fout << results[kp][0] << " " << results[kp][1] << " "
             << results[kp][2] << " " << results[kp][3] << "\n";
    }
    fout.close();
    std::cerr << "Done. Processed " << n_kp << " kinematic points." << std::endl;
    return 0;
}